//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseFirstMigration
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PostsDataBaseFirstEntities : DbContext
    {
        public PostsDataBaseFirstEntities()
            : base("name=PostsDataBaseFirstEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Post> Posts { get; set; }
    }
}
